// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHEEjaqKorH7_SxjIOmwHchZfmo7tTdfc',
    appId: '1:421095890359:web:6ee0b73c60e8fcafda9c32',
    messagingSenderId: '421095890359',
    projectId: 'test-a7179',
    authDomain: 'test-a7179.firebaseapp.com',
    databaseURL: 'https://test-a7179-default-rtdb.firebaseio.com',
    storageBucket: 'test-a7179.firebasestorage.app',
    measurementId: 'G-45KBJG8NL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChM_ZvYeoXdcStGJiVTNWwncO9YYtCgwM',
    appId: '1:421095890359:android:5be9c30ebf77740fda9c32',
    messagingSenderId: '421095890359',
    projectId: 'test-a7179',
    databaseURL: 'https://test-a7179-default-rtdb.firebaseio.com',
    storageBucket: 'test-a7179.firebasestorage.app',
  );

}