// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU72LwoqwfQHP31xkMVWtQG14ZnEgOztM',
    appId: '1:95063495910:web:6b6a49d521bbf80246d727',
    messagingSenderId: '95063495910',
    projectId: 'dahee-flutter-lecture',
    authDomain: 'dahee-flutter-lecture.firebaseapp.com',
    storageBucket: 'dahee-flutter-lecture.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI-KR1PT1qlRTBfX8iQP_VX6yp0yuOYCE',
    appId: '1:95063495910:android:5af4ed236e92264746d727',
    messagingSenderId: '95063495910',
    projectId: 'dahee-flutter-lecture',
    storageBucket: 'dahee-flutter-lecture.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU72LwoqwfQHP31xkMVWtQG14ZnEgOztM',
    appId: '1:95063495910:web:bf464c0b62a8b0c746d727',
    messagingSenderId: '95063495910',
    projectId: 'dahee-flutter-lecture',
    authDomain: 'dahee-flutter-lecture.firebaseapp.com',
    storageBucket: 'dahee-flutter-lecture.firebasestorage.app',
  );
}
